
service: s3-enc-enforce
provider:
  name: aws
  runtime: python3.6
  region: eu-west-1

# Not sure why this didn't work :(
#
# iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"
#    - Effect: "Allow"
#      Action:
#        - "ses:SendEmail"
#        - "ses:SendRawEmail"
#      Resource:
#          - "arn:aws:ses:eu-west-1::identity/emre@contino.io"

functions:
  enforce:
    handler: src.handler.main
    events:
      - s3:
        bucket: "*"
        event: s3:createBucket:*
